-- Source database scaffold (PostgreSQL 16).
-- Converted from db/raw-dumps/faker_*.sql (MySQL 8.0 mysqldump).
-- Identifiers: camelCase preserved, double-quoted (PG folds unquoted to lowercase).
-- Idempotent: DROP ... CASCADE first, safe to re-run via init_source.sh
--             and safe as a /docker-entrypoint-initdb.d auto-init script.
-- NOTE: inferred FKs (courierId, userId, deliveryRiderId) are enforced here;
--       orphan rows in dumps will fail fast at import — that's intentional.

DROP TABLE IF EXISTS "OrderItems" CASCADE;
DROP TABLE IF EXISTS "Orders" CASCADE;
DROP TABLE IF EXISTS "Products" CASCADE;
DROP TABLE IF EXISTS "Users" CASCADE;
DROP TABLE IF EXISTS "Riders" CASCADE;
DROP TABLE IF EXISTS "Couriers" CASCADE;

CREATE TABLE "Couriers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255),
  "createdAt" TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP NOT NULL
);

CREATE TABLE "Riders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "firstName" VARCHAR(255),
  "lastName" VARCHAR(255),
  "vehicleType" VARCHAR(255),
  "courierId" INTEGER REFERENCES "Couriers" ("id"),
  "age" INTEGER,
  "gender" VARCHAR(255),
  "createdAt" TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP NOT NULL
);

CREATE TABLE "Users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" VARCHAR(255),
  "firstName" VARCHAR(255),
  "lastName" VARCHAR(255),
  "address1" VARCHAR(255),
  "address2" VARCHAR(255),
  "city" VARCHAR(255),
  "country" VARCHAR(255),
  "zipCode" VARCHAR(255),
  "phoneNumber" VARCHAR(255),
  -- ETL NOTE (Phase 3): kept VARCHAR to mimic the raw dump. Values use mixed
  -- formats (same faker pipeline as Orders.deliveryDate: 'YYYY-MM-DD' and
  -- 'MM/DD/YYYY'). transform.py must parse + cast to DATE before loading the
  -- warehouse. Do NOT "fix" by altering this column type here.
  "dateOfBirth" VARCHAR(255),
  "gender" VARCHAR(255),
  "createdAt" TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP NOT NULL
);

CREATE TABLE "Products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "productCode" VARCHAR(255),
  "category" VARCHAR(255),
  "description" VARCHAR(255),
  "name" VARCHAR(255),
  "price" REAL,
  "createdAt" TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP NOT NULL
);

CREATE TABLE "Orders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderNumber" VARCHAR(255),
  "userId" INTEGER REFERENCES "Users" ("id"),
  -- ETL NOTE (Phase 3): kept VARCHAR to mimic the raw dump. Mixed formats
  -- observed in dump: '2025-05-24' and '06/25/2025'. transform.py must parse
  -- + cast to DATE before loading the warehouse. Do NOT "fix" here.
  "deliveryDate" VARCHAR(255),
  "deliveryRiderId" INTEGER REFERENCES "Riders" ("id"),
  "createdAt" TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP NOT NULL
);

CREATE TABLE "OrderItems" (
  "quantity" INTEGER,
  "notes" VARCHAR(255),
  "createdAt" TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP NOT NULL,
  "OrderId" INTEGER NOT NULL REFERENCES "Orders" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "ProductId" INTEGER NOT NULL REFERENCES "Products" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY ("OrderId", "ProductId")
);
