-- Canonical source database DDL (PostgreSQL 16).
-- Converted from the six MySQL 8.0 dumps in the official archive.
-- Single source of truth: read by the streaming importer (db/source/importer/cli.js)
-- and auto-applied by Postgres on first volume init via
-- ./db/source/init:/docker-entrypoint-initdb.d:ro (see docker-compose.yml).
-- Only constraints declared by those dumps are reproduced (UNDECLARED edges
-- courierId/userId/deliveryRiderId are COUNTED by the importer as orphans,
-- not enforced here, so bad archives report per-relationship counts instead
-- of aborting mid-COPY on a hard FK).
-- Idempotent: DROP ... CASCADE first, safe to re-run via db/scripts/setup_source.sh --schema-only
--             and safe as a /docker-entrypoint-initdb.d auto-init script.
-- ETL NOTE (Phase 3): Users.dateOfBirth and Orders.deliveryDate stay VARCHAR
-- to mimic the raw dump (mixed 'YYYY-MM-DD' and 'MM/DD/YYYY'). transform.py
-- must parse + cast to DATE before loading the warehouse. Do NOT "fix" here.
-- Products.price stays REAL to mimic the dump; warehouse casts to NUMERIC(12,2).

DROP TABLE IF EXISTS "OrderItems" CASCADE;
DROP TABLE IF EXISTS "Orders" CASCADE;
DROP TABLE IF EXISTS "Products" CASCADE;
DROP TABLE IF EXISTS "Users" CASCADE;
DROP TABLE IF EXISTS "Riders" CASCADE;
DROP TABLE IF EXISTS "Couriers" CASCADE;

CREATE TABLE "Couriers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255),
  "createdAt" TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP NOT NULL
);

CREATE TABLE "Riders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "firstName" VARCHAR(255),
  "lastName" VARCHAR(255),
  "vehicleType" VARCHAR(255),
  "courierId" INTEGER,
  "age" INTEGER,
  "gender" VARCHAR(255),
  "createdAt" TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP NOT NULL
);

CREATE TABLE "Users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" VARCHAR(255),
  "firstName" VARCHAR(255),
  "lastName" VARCHAR(255),
  "address1" VARCHAR(255),
  "address2" VARCHAR(255),
  "city" VARCHAR(255),
  "country" VARCHAR(255),
  "zipCode" VARCHAR(255),
  "phoneNumber" VARCHAR(255),
  "dateOfBirth" VARCHAR(255),
  "gender" VARCHAR(255),
  "createdAt" TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP NOT NULL
);

CREATE TABLE "Products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "productCode" VARCHAR(255),
  "category" VARCHAR(255),
  "description" VARCHAR(255),
  "name" VARCHAR(255),
  "price" REAL,
  "createdAt" TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP NOT NULL
);

CREATE TABLE "Orders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderNumber" VARCHAR(255),
  "userId" INTEGER,
  "deliveryDate" VARCHAR(255),
  "deliveryRiderId" INTEGER,
  "createdAt" TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP NOT NULL
);

CREATE TABLE "OrderItems" (
  "quantity" INTEGER,
  "notes" VARCHAR(255),
  "createdAt" TIMESTAMP NOT NULL,
  "updatedAt" TIMESTAMP NOT NULL,
  "OrderId" INTEGER NOT NULL REFERENCES "Orders" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "ProductId" INTEGER NOT NULL REFERENCES "Products" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY ("OrderId", "ProductId")
);

CREATE INDEX "OrderItems_ProductId_idx" ON "OrderItems" ("ProductId");
