-- Data warehouse DDL (PostgreSQL 16). Star schema, 9 tables.
-- Conventions, corrections, and verification: docs/database/data-warehouse-implementation.md.
-- Design reference: docs/database/data-warehouse-schema.md.

DROP TABLE IF EXISTS "FACT_RIDERDAILY" CASCADE;
DROP TABLE IF EXISTS "FACT_ORDERITEM" CASCADE;
DROP TABLE IF EXISTS "FACT_ORDERDELIVERY" CASCADE;
DROP TABLE IF EXISTS "DIM_DATE" CASCADE;
DROP TABLE IF EXISTS "DIM_RIDER" CASCADE;
DROP TABLE IF EXISTS "DIM_GEOGRAPHY" CASCADE;
DROP TABLE IF EXISTS "DIM_ORDERSIZE" CASCADE;
DROP TABLE IF EXISTS "DIM_CUSTOMER" CASCADE;
DROP TABLE IF EXISTS "DIM_PRODUCT" CASCADE;

CREATE TABLE "DIM_DATE" (
  "dateKey" INTEGER PRIMARY KEY,
  "fullDate" DATE NOT NULL UNIQUE,
  "dayOfMonth" SMALLINT NOT NULL,
  "dayName" VARCHAR(9) NOT NULL,
  "isWeekend" BOOLEAN NOT NULL,
  "isPayDay" BOOLEAN NOT NULL,
  "weekOfYear" SMALLINT NOT NULL,
  "monthNumber" SMALLINT NOT NULL,
  "monthName" VARCHAR(9) NOT NULL,
  "quarter" SMALLINT NOT NULL,
  "year" SMALLINT NOT NULL
);

CREATE TABLE "DIM_RIDER" (
  "riderKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "riderId" INTEGER NOT NULL UNIQUE,
  "fullName" VARCHAR(511) NOT NULL,
  "vehicleType" VARCHAR(32) NOT NULL,
  "courierId" INTEGER NOT NULL,
  "courierName" VARCHAR(255) NOT NULL,
  "age" INTEGER,
  "ageBand" VARCHAR(16),
  "gender" CHAR(1) NOT NULL
);

CREATE TABLE "DIM_GEOGRAPHY" (
  "geoKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "country" VARCHAR(128) NOT NULL,
  "city" VARCHAR(128) NOT NULL,
  "zipCode" VARCHAR(32) NOT NULL,
  UNIQUE ("country", "city", "zipCode")
);

CREATE TABLE "DIM_ORDERSIZE" (
  "orderSizeKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sizeName" VARCHAR(16) NOT NULL UNIQUE,
  "sizeGroup" VARCHAR(16) NOT NULL,
  "minQuantity" INTEGER NOT NULL,
  "maxQuantity" INTEGER NOT NULL
);

CREATE TABLE "DIM_CUSTOMER" (
  "customerKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customerId" INTEGER NOT NULL UNIQUE,
  "username" VARCHAR(255) NOT NULL,
  "firstName" VARCHAR(255),
  "lastName" VARCHAR(255),
  "gender" CHAR(1)
);

CREATE TABLE "DIM_PRODUCT" (
  "productKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "productId" INTEGER NOT NULL UNIQUE,
  "productCode" VARCHAR(64) NOT NULL,
  "productName" VARCHAR(255) NOT NULL,
  "category" VARCHAR(128) NOT NULL,
  "listPrice" NUMERIC(12,2) NOT NULL
);

CREATE TABLE "FACT_ORDERDELIVERY" (
  "orderDeliveryKey" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderNumber" VARCHAR(255) NOT NULL,
  "deliveryDateKey" INTEGER NOT NULL REFERENCES "DIM_DATE" ("dateKey"),
  "riderKey" INTEGER NOT NULL REFERENCES "DIM_RIDER" ("riderKey"),
  "geoKey" INTEGER NOT NULL REFERENCES "DIM_GEOGRAPHY" ("geoKey"),
  "orderSizeKey" INTEGER NOT NULL REFERENCES "DIM_ORDERSIZE" ("orderSizeKey"),
  "customerKey" INTEGER NOT NULL REFERENCES "DIM_CUSTOMER" ("customerKey"),
  "orderCount" INTEGER NOT NULL DEFAULT 1 CHECK ("orderCount" = 1),
  "totalQuantity" INTEGER NOT NULL,
  "lineItemCount" INTEGER NOT NULL
);

CREATE TABLE "FACT_ORDERITEM" (
  "orderItemKey" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderNumber" VARCHAR(255) NOT NULL,
  "deliveryDateKey" INTEGER NOT NULL REFERENCES "DIM_DATE" ("dateKey"),
  "riderKey" INTEGER NOT NULL REFERENCES "DIM_RIDER" ("riderKey"),
  "geoKey" INTEGER NOT NULL REFERENCES "DIM_GEOGRAPHY" ("geoKey"),
  "orderSizeKey" INTEGER NOT NULL REFERENCES "DIM_ORDERSIZE" ("orderSizeKey"),
  "customerKey" INTEGER NOT NULL REFERENCES "DIM_CUSTOMER" ("customerKey"),
  "productKey" INTEGER NOT NULL REFERENCES "DIM_PRODUCT" ("productKey"),
  "quantity" INTEGER NOT NULL,
  "lineValue" NUMERIC(12,2) NOT NULL
);

CREATE TABLE "FACT_RIDERDAILY" (
  "riderDailyKey" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dateKey" INTEGER NOT NULL REFERENCES "DIM_DATE" ("dateKey"),
  "riderKey" INTEGER NOT NULL REFERENCES "DIM_RIDER" ("riderKey"),
  "ordersDelivered" INTEGER NOT NULL,
  "itemsDelivered" INTEGER NOT NULL,
  "maxBasket" INTEGER NOT NULL,
  "isActiveDay" SMALLINT NOT NULL CHECK ("isActiveDay" IN (0, 1))
);

INSERT INTO "DIM_RIDER"
  ("riderKey", "riderId", "fullName", "vehicleType", "courierId", "courierName", "age", "ageBand", "gender")
OVERRIDING SYSTEM VALUE VALUES
  (0, -1, 'Unknown', 'Unknown', -1, 'Unknown', NULL, 'Unknown', 'U');

INSERT INTO "DIM_GEOGRAPHY" ("geoKey", "country", "city", "zipCode")
OVERRIDING SYSTEM VALUE VALUES
  (0, 'Unknown', 'Unknown', 'Unknown');

INSERT INTO "DIM_ORDERSIZE"
  ("orderSizeKey", "sizeName", "sizeGroup", "minQuantity", "maxQuantity")
OVERRIDING SYSTEM VALUE VALUES
  (0, 'Unknown', 'Unknown', 0, 0),
  (1, 'Small', 'Light', 1, 1),
  (2, 'Medium', 'Light', 2, 5),
  (3, 'Large', 'Heavy', 6, 20),
  (4, 'Bulk', 'Heavy', 21, 2147483647);

INSERT INTO "DIM_CUSTOMER"
  ("customerKey", "customerId", "username", "firstName", "lastName", "gender")
OVERRIDING SYSTEM VALUE VALUES
  (0, -1, 'Unknown', 'Unknown', 'Unknown', NULL);

INSERT INTO "DIM_PRODUCT"
  ("productKey", "productId", "productCode", "productName", "category", "listPrice")
OVERRIDING SYSTEM VALUE VALUES
  (0, -1, 'Unknown', 'Unknown', 'Unknown', 0.00);

ALTER TABLE "DIM_RIDER" ALTER COLUMN "riderKey" RESTART WITH 1;
ALTER TABLE "DIM_GEOGRAPHY" ALTER COLUMN "geoKey" RESTART WITH 1;
ALTER TABLE "DIM_ORDERSIZE" ALTER COLUMN "orderSizeKey" RESTART WITH 5;
ALTER TABLE "DIM_CUSTOMER" ALTER COLUMN "customerKey" RESTART WITH 1;
ALTER TABLE "DIM_PRODUCT" ALTER COLUMN "productKey" RESTART WITH 1;
