-- Canonical data warehouse DDL (PostgreSQL 16).
-- Star schema: 6 conformed dimensions + 3 fact tables. Design reference:
-- docs/database/data-warehouse-schema.md; build record with applied
-- profiling corrections: docs/database/data-warehouse-implementation.md.
-- Identifiers: quoted UPPERCASE exactly as the design doc names them.
-- Idempotent: DROP ... CASCADE first, safe to re-run anytime and safe as a
-- /docker-entrypoint-initdb.d auto-init script (dw_db service).
-- Keys: DIM_DATE.dateKey is a smart YYYYMMDD key; other dimensions and all
-- facts use GENERATED ... AS IDENTITY surrogates. Every dimension except
-- DIM_DATE ships a key-0 Unknown row so ETL maps missing references to 0,
-- never to NULL FKs. (Unparseable delivery dates are rejected/quarantined
-- at ETL time, so DIM_DATE has no Unknown member.)
-- Money is NUMERIC(12,2) throughout; source REAL prices are never summed.
-- PK/UNIQUE only: secondary indexes belong to Step 6 (performance testing).

DROP TABLE IF EXISTS "FACT_RIDERDAILY" CASCADE;
DROP TABLE IF EXISTS "FACT_ORDERITEM" CASCADE;
DROP TABLE IF EXISTS "FACT_ORDERDELIVERY" CASCADE;
DROP TABLE IF EXISTS "DIM_DATE" CASCADE;
DROP TABLE IF EXISTS "DIM_RIDER" CASCADE;
DROP TABLE IF EXISTS "DIM_GEOGRAPHY" CASCADE;
DROP TABLE IF EXISTS "DIM_ORDERSIZE" CASCADE;
DROP TABLE IF EXISTS "DIM_CUSTOMER" CASCADE;
DROP TABLE IF EXISTS "DIM_PRODUCT" CASCADE;

CREATE TABLE "DIM_DATE" (
  "dateKey" INTEGER PRIMARY KEY,
  "fullDate" DATE NOT NULL UNIQUE,
  "dayOfMonth" SMALLINT NOT NULL,
  "dayName" VARCHAR(9) NOT NULL,
  "isWeekend" BOOLEAN NOT NULL,
  -- Q14 rule: 15th and last day of month (semimonthly payroll convention).
  "isPayDay" BOOLEAN NOT NULL,
  "weekOfYear" SMALLINT NOT NULL,
  "monthNumber" SMALLINT NOT NULL,
  "monthName" VARCHAR(9) NOT NULL,
  "quarter" SMALLINT NOT NULL,
  "year" SMALLINT NOT NULL
);

CREATE TABLE "DIM_RIDER" (
  "riderKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "riderId" INTEGER NOT NULL UNIQUE,
  "fullName" VARCHAR(511) NOT NULL,
  "vehicleType" VARCHAR(32) NOT NULL,
  "courierId" INTEGER NOT NULL,
  "courierName" VARCHAR(255) NOT NULL,
  "age" INTEGER,
  -- Kept: Q8/Q12 need rider bands; the profiling flag was customers-only.
  "ageBand" VARCHAR(16),
  "gender" CHAR(1) NOT NULL
);

CREATE TABLE "DIM_GEOGRAPHY" (
  "geoKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "country" VARCHAR(128) NOT NULL,
  "city" VARCHAR(128) NOT NULL,
  "zipCode" VARCHAR(32) NOT NULL,
  UNIQUE ("country", "city", "zipCode")
);

CREATE TABLE "DIM_ORDERSIZE" (
  "orderSizeKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sizeName" VARCHAR(16) NOT NULL UNIQUE,
  "sizeGroup" VARCHAR(16) NOT NULL,
  "minQuantity" INTEGER NOT NULL,
  "maxQuantity" INTEGER NOT NULL
);

CREATE TABLE "DIM_CUSTOMER" (
  "customerKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customerId" INTEGER NOT NULL UNIQUE,
  "username" VARCHAR(255) NOT NULL,
  "firstName" VARCHAR(255),
  "lastName" VARCHAR(255),
  "gender" CHAR(1)
);
-- No ageBand: source customers are effectively single-age (profiling), so the
-- column would be constant. Hierarchy collapses to Gender; Q22 answers the
-- concentration half only.

CREATE TABLE "DIM_PRODUCT" (
  "productKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "productId" INTEGER NOT NULL UNIQUE,
  "productCode" VARCHAR(64) NOT NULL,
  "productName" VARCHAR(255) NOT NULL,
  "category" VARCHAR(128) NOT NULL,
  "listPrice" NUMERIC(12,2) NOT NULL
);

CREATE TABLE "FACT_ORDERDELIVERY" (
  "orderDeliveryKey" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderNumber" VARCHAR(255) NOT NULL,
  "deliveryDateKey" INTEGER NOT NULL REFERENCES "DIM_DATE" ("dateKey"),
  "riderKey" INTEGER NOT NULL REFERENCES "DIM_RIDER" ("riderKey"),
  "geoKey" INTEGER NOT NULL REFERENCES "DIM_GEOGRAPHY" ("geoKey"),
  "orderSizeKey" INTEGER NOT NULL REFERENCES "DIM_ORDERSIZE" ("orderSizeKey"),
  "customerKey" INTEGER NOT NULL REFERENCES "DIM_CUSTOMER" ("customerKey"),
  "orderCount" INTEGER NOT NULL DEFAULT 1 CHECK ("orderCount" = 1),
  "totalQuantity" INTEGER NOT NULL,
  "lineItemCount" INTEGER NOT NULL
);

CREATE TABLE "FACT_ORDERITEM" (
  "orderItemKey" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderNumber" VARCHAR(255) NOT NULL,
  "deliveryDateKey" INTEGER NOT NULL REFERENCES "DIM_DATE" ("dateKey"),
  "riderKey" INTEGER NOT NULL REFERENCES "DIM_RIDER" ("riderKey"),
  "geoKey" INTEGER NOT NULL REFERENCES "DIM_GEOGRAPHY" ("geoKey"),
  "orderSizeKey" INTEGER NOT NULL REFERENCES "DIM_ORDERSIZE" ("orderSizeKey"),
  "customerKey" INTEGER NOT NULL REFERENCES "DIM_CUSTOMER" ("customerKey"),
  "productKey" INTEGER NOT NULL REFERENCES "DIM_PRODUCT" ("productKey"),
  "quantity" INTEGER NOT NULL,
  -- Indicative basket value (quantity x current list price), NOT revenue:
  -- OrderItems carries no historical price.
  "lineValue" NUMERIC(12,2) NOT NULL
);

CREATE TABLE "FACT_RIDERDAILY" (
  "riderDailyKey" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dateKey" INTEGER NOT NULL REFERENCES "DIM_DATE" ("dateKey"),
  "riderKey" INTEGER NOT NULL REFERENCES "DIM_RIDER" ("riderKey"),
  "ordersDelivered" INTEGER NOT NULL,
  "itemsDelivered" INTEGER NOT NULL,
  -- Non-additive: peak-day basket, never summed across days.
  "maxBasket" INTEGER NOT NULL,
  "isActiveDay" SMALLINT NOT NULL CHECK ("isActiveDay" IN (0, 1))
);

-- Unknown members (key 0; ETL maps missing references here, never to NULL).
INSERT INTO "DIM_RIDER"
  ("riderKey", "riderId", "fullName", "vehicleType", "courierId", "courierName", "age", "ageBand", "gender")
OVERRIDING SYSTEM VALUE VALUES
  (0, -1, 'Unknown', 'Unknown', -1, 'Unknown', NULL, 'Unknown', 'U');

INSERT INTO "DIM_GEOGRAPHY" ("geoKey", "country", "city", "zipCode")
OVERRIDING SYSTEM VALUE VALUES
  (0, 'Unknown', 'Unknown', 'Unknown');

INSERT INTO "DIM_ORDERSIZE"
  ("orderSizeKey", "sizeName", "sizeGroup", "minQuantity", "maxQuantity")
OVERRIDING SYSTEM VALUE VALUES
  (0, 'Unknown', 'Unknown', 0, 0),
  (1, 'Small', 'Light', 1, 1),
  (2, 'Medium', 'Light', 2, 5),
  (3, 'Large', 'Heavy', 6, 20),
  (4, 'Bulk', 'Heavy', 21, 2147483647);

INSERT INTO "DIM_CUSTOMER"
  ("customerKey", "customerId", "username", "firstName", "lastName", "gender")
OVERRIDING SYSTEM VALUE VALUES
  (0, -1, 'Unknown', 'Unknown', 'Unknown', NULL);

INSERT INTO "DIM_PRODUCT"
  ("productKey", "productId", "productCode", "productName", "category", "listPrice")
OVERRIDING SYSTEM VALUE VALUES
  (0, -1, 'Unknown', 'Unknown', 'Unknown', 0.00);

-- Restart identity sequences past the seeded keys so generated values never
-- collide with Unknown (0) or the static order-size bands (0-4).
ALTER TABLE "DIM_RIDER" ALTER COLUMN "riderKey" RESTART WITH 1;
ALTER TABLE "DIM_GEOGRAPHY" ALTER COLUMN "geoKey" RESTART WITH 1;
ALTER TABLE "DIM_ORDERSIZE" ALTER COLUMN "orderSizeKey" RESTART WITH 5;
ALTER TABLE "DIM_CUSTOMER" ALTER COLUMN "customerKey" RESTART WITH 1;
ALTER TABLE "DIM_PRODUCT" ALTER COLUMN "productKey" RESTART WITH 1;
